# Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.
print('Fala um numero que eu te mostro a tabuada desse numero.')
n1 = int(input('Numero:'))
print('{}x1={}'.format(n1, n1 * 1))
print('{}x2={}'.format(n1, n1 * 2))
print('{}x3={}'.format(n1, n1 * 3))
print('{}x4={}'.format(n1, n1 * 4))
print('{}x5={}'.format(n1, n1 * 5))
print('{}x6={}'.format(n1, n1 * 6))
print('{}x7={}'.format(n1, n1 * 7))
print('{}x8={}'.format(n1, n1 * 8))
print('{}x9={}'.format(n1, n1 * 9))
print('{}x10={}'.format(n1, n1 * 10))
